baseurl: "https://1000ch.net/"
title: "1000ch.net"
footnotereturnlinkcontents: "↩"
contentdir: "content"
layoutdir: "layouts"
staticdir: "static"
publishdir: "public"
uglyUrls: true
metaDataFormat: "yaml"
params:
  author: "1000ch"
permalinks:
  post: "/:year/:title"
